// Stage the generated spec into public/ for the renderer. Prefers the real
// spec.json (override via SPEC_PATH), falls back to sample-spec.json so the
// Phase 1-3 skeleton still renders. Dest is always public/spec.json.
import {copyFileSync, existsSync, mkdirSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const remotionRoot = resolve(__dirname, '..');
const repoRoot = resolve(remotionRoot, '..');

const override = process.env.SPEC_PATH ? resolve(repoRoot, process.env.SPEC_PATH) : null;
const generated = resolve(repoRoot, 'spec.json');
const sample = resolve(repoRoot, 'sample-spec.json');
const src = [override, generated, sample].find((p) => p && existsSync(p));

if (!src) {
  console.error('[copy-spec] no spec.json or sample-spec.json found');
  process.exit(1);
}

const publicDir = resolve(remotionRoot, 'public');
mkdirSync(publicDir, {recursive: true});
copyFileSync(src, resolve(publicDir, 'spec.json'));
console.log(`[copy-spec] ${src} -> public/spec.json`);

// The voiceover wav is generated by the voice stage and gitignored (only its path
// string lives in specs), but motion renders PROBE the audio file — a fresh clone
// rendering the demo specs needs a real wav at the referenced path. Synthesize 1s
// of silence there when (and only when) no generated voiceover exists yet.
const voiceoverPath = resolve(publicDir, 'assets', 'voiceover.wav');
if (!existsSync(voiceoverPath)) {
  const sampleRate = 44100;
  const numSamples = sampleRate; // 1 second, mono, 16-bit PCM
  const dataSize = numSamples * 2;
  const wav = Buffer.alloc(44 + dataSize); // header + silent samples (zeros)
  wav.write('RIFF', 0);
  wav.writeUInt32LE(36 + dataSize, 4);
  wav.write('WAVE', 8);
  wav.write('fmt ', 12);
  wav.writeUInt32LE(16, 16); // PCM fmt chunk size
  wav.writeUInt16LE(1, 20); // PCM
  wav.writeUInt16LE(1, 22); // mono
  wav.writeUInt32LE(sampleRate, 24);
  wav.writeUInt32LE(sampleRate * 2, 28); // byte rate
  wav.writeUInt16LE(2, 32); // block align
  wav.writeUInt16LE(16, 34); // bits per sample
  wav.write('data', 36);
  wav.writeUInt32LE(dataSize, 40);
  mkdirSync(dirname(voiceoverPath), {recursive: true});
  writeFileSync(voiceoverPath, wav);
  console.log('[copy-spec] no voiceover yet -> wrote 1s silent placeholder to public/assets/voiceover.wav');
}
