"""Hero background contrast gate — OV-7 (Studio v3 M4 T4).

Renders a HOOK frame two ways:
  (a) with-clip   — busy test-pattern clip as backgroundClip (adversarial case)
  (b) baseline    — no clip (gradient-only, opaque card)

Metric: worst-case LOCAL contrast (OV-7 ruling).
  - Tile the text region (ground-truth where hook text sits in the 1080x1920 frame).
  - Per tile: compute Michelson contrast = (Lmax - Lmin) / (Lmax + Lmin) using the
    5th-percentile luminance (darkest, i.e. background-like) and 95th-percentile
    luminance (brightest, i.e. text-like) within that tile.
  - Assert minimum-tile contrast in the with-clip render ≥ minimum-tile contrast in
    the baseline × TOLERANCE (default 0.90 — the scrim must keep worst-case local
    legibility within 10% of the opaque card).

Mean contrast is deliberately NOT used: a scrim lowers the mean while busy mid-tone
texture destroys local legibility without moving it — the mean version can never fail.

Usage:
  backend/.venv/bin/python backend/scripts/hero_bg_gate.py

Outputs:
  /tmp/hero_bg_gate/hook-with-clip.png
  /tmp/hero_bg_gate/hook-baseline.png

Exit 0 → PASS (both contrast numbers printed)
Exit 1 → FAIL or render error
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]
REMOTION = ROOT / "remotion"
PUBLIC = REMOTION / "public"
ASSETS = PUBLIC / "assets"
GATE_OUT = Path("/tmp/hero_bg_gate")

# ---------------------------------------------------------------------------
# Gate parameters
# ---------------------------------------------------------------------------
RENDER_FRAME = 15            # mid-scene frame (motion has settled, text visible)
HOOK_TITLE = "Why is the ocean blue?"
HOOK_SUBTITLE = "Ocean facts"
FPS = 30
DURATION = 90                # 3-second hook scene in frames

# Text region bounding box in the 1080x1920 frame.
#   Layout: padding='0 96px', alignItems/justifyContent='center', maxWidth=900.
#   heroFontSize("Why is the ocean blue?") → 104px (22 chars, >18 → 104).
#   Centered vertically at ~960px. Title + subtitle span ~300px vertically.
#   Confirmed by pixel analysis: bright rows run from y≈800 to y≈1080.
TEXT_REGION = {"x": 90, "y": 790, "w": 900, "h": 300}

# Tile grid: 6 columns × 6 rows inside the text region
TILE_COLS = 6
TILE_ROWS = 6

# Minimum p95 luminance for a tile to be considered "text-bearing".
# Tiles below this threshold contain only background (no glyphs) — skipping
# them prevents dark-corner false-failures where the metric is vacuous.
MIN_TEXT_TILE_LUM = 0.05

# Contrast tolerance: with-clip min-tile ≥ baseline min-tile × TOLERANCE
TOLERANCE = 0.90

# Busy test-pattern clip (generated by hero_bg_gate setup; the adversarial case).
# The clip is shorter than DURATION (3s = 90 frames) so it would loop — but
# for a still render of frame 15 this doesn't matter.
BUSY_CLIP_SRC = "assets/busy_test_pattern.mp4"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def base_spec(with_clip: bool) -> dict:
    """Build a minimal single-scene hook spec for the gate render."""
    template_props: dict = {
        "title": HOOK_TITLE,
        "subtitle": HOOK_SUBTITLE,
    }
    if with_clip:
        template_props["backgroundClip"] = {
            "type": "video",
            "src": BUSY_CLIP_SRC,
            "fit": "cover",
            "kenBurns": {
                "from": 1.0,
                "to": 1.08,
                "originX": 0.5,
                "originY": 0.5,
            },
            "loop": True,
        }

    return {
        "meta": {
            "title": "hero-bg-gate",
            "fps": FPS,
            "width": 1080,
            "height": 1920,
            "durationInFrames": DURATION,
        },
        "theme": _base_theme(),
        "audio": {
            "voiceover": "assets/voiceover.wav",
            "music": None,
            "musicVolumeDb": -18.0,
        },
        "captions": [],
        "scenes": [
            {
                "id": "scene-0",
                "startFrame": 0,
                "durationInFrames": DURATION,
                "template": "hook",
                "templateProps": template_props,
                "media": None,
                "transition": None,
            }
        ],
        "layers": [],
    }


def _base_theme() -> dict:
    """Read the current theme from spec.json (whichever exists), or use a default."""
    for candidate in [ROOT / "spec.json", PUBLIC / "spec.json"]:
        if candidate.exists():
            try:
                return json.loads(candidate.read_text())["theme"]
            except (KeyError, json.JSONDecodeError):
                pass
    # Fallback: a dark theme that exercises the scrim contrast correctly.
    return {
        "palette": {
            "background": "#0a0a1a",
            "foreground": "#ffffff",
            "accent": "#ffe600",
            "muted": "#9ca3af",
        },
        "fonts": {"heading": "Inter", "body": "Inter"},
        "transition": "fade",
        "caption": {
            "fontFamily": "Inter",
            "fontWeight": 800,
            "color": "#FFFFFF",
            "highlightColor": "#ffe600",
            "strokeColor": "#000000",
            "positionY": 0.85,
        },
    }


def stage_spec(spec: dict) -> None:
    """Write spec to both spec.json locations the renderer reads."""
    data = json.dumps(spec, indent=2)
    (ROOT / "spec.json").write_text(data)
    PUBLIC.mkdir(parents=True, exist_ok=True)
    (PUBLIC / "spec.json").write_text(data)


def render_still(label: str, frame: int, out_png: Path) -> None:
    """Render a single Remotion still frame into out_png."""
    out_png.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        ["npx", "remotion", "still", "Video", str(out_png), f"--frame={frame}"],
        cwd=str(REMOTION),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"[gate] STDERR from remotion still ({label}):", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        raise RuntimeError(f"remotion still failed for {label} (exit {result.returncode})")
    print(f"[gate] rendered  {label} → {out_png}")


# ---------------------------------------------------------------------------
# Contrast metric — min-tile luminance contrast
# ---------------------------------------------------------------------------

def relative_luminance(rgb: np.ndarray) -> np.ndarray:
    """WCAG relative luminance from linear sRGB (shape: [H, W, 3] uint8 → [H, W])."""
    srgb = rgb.astype(np.float32) / 255.0
    # Linearise via sRGB transfer function
    linear = np.where(srgb <= 0.04045, srgb / 12.92, ((srgb + 0.055) / 1.055) ** 2.4)
    # ITU-R BT.709 luma weights
    return 0.2126 * linear[..., 0] + 0.7152 * linear[..., 1] + 0.0722 * linear[..., 2]


def tile_min_contrast(png_path: Path) -> tuple[float, int]:
    """Compute the minimum Michelson contrast over text-bearing tiles in the text region.

    Per tile:
      - 5th-percentile luminance  → L_dark  (background-like dark pixels)
      - 95th-percentile luminance → L_light (text-like light pixels)
      - Michelson contrast = (L_light - L_dark) / (L_light + L_dark + 1e-6)

    Tiles whose p95 luminance < MIN_TEXT_TILE_LUM are pure-background (no glyphs)
    and are skipped — their contrast is vacuous (both L_dark and L_light are in the
    same dark range with no text pixels to evaluate legibility against).

    Return (minimum contrast across active tiles, number of active tiles evaluated).
    """
    img = Image.open(png_path).convert("RGB")
    arr = np.array(img)                    # [H, W, 3] uint8
    lum = relative_luminance(arr)          # [H, W] float32

    x0 = TEXT_REGION["x"]
    y0 = TEXT_REGION["y"]
    W = TEXT_REGION["w"]
    H = TEXT_REGION["h"]

    tile_w = W // TILE_COLS
    tile_h = H // TILE_ROWS

    min_contrast = float("inf")
    active_tiles = 0
    for row in range(TILE_ROWS):
        for col in range(TILE_COLS):
            tx = x0 + col * tile_w
            ty = y0 + row * tile_h
            tile = lum[ty: ty + tile_h, tx: tx + tile_w]
            if tile.size == 0:
                continue
            l_dark = float(np.percentile(tile, 5))
            l_light = float(np.percentile(tile, 95))
            # Skip pure-background tiles — no glyphs means no legibility to measure.
            if l_light < MIN_TEXT_TILE_LUM:
                continue
            active_tiles += 1
            c = (l_light - l_dark) / (l_light + l_dark + 1e-6)
            if c < min_contrast:
                min_contrast = c

    if active_tiles == 0:
        # Fallback: no text-bearing tiles found — use the full-region global value.
        l_dark = float(np.percentile(lum[y0: y0 + H, x0: x0 + W], 5))
        l_light = float(np.percentile(lum[y0: y0 + H, x0: x0 + W], 95))
        return (l_light - l_dark) / (l_light + l_dark + 1e-6), 0

    return min_contrast, active_tiles


# ---------------------------------------------------------------------------
# Main gate
# ---------------------------------------------------------------------------

def main() -> int:
    GATE_OUT.mkdir(parents=True, exist_ok=True)

    png_clip = GATE_OUT / "hook-with-clip.png"
    png_base = GATE_OUT / "hook-baseline.png"

    # --- Verify the busy clip exists ---
    busy_clip_abs = ASSETS / "busy_test_pattern.mp4"
    if not busy_clip_abs.exists():
        print(
            f"[gate] FAIL — busy test-pattern clip not found at {busy_clip_abs}.\n"
            "Generate it with:\n"
            "  ffmpeg -y -f lavfi -i 'testsrc2=size=1080x1920:rate=30:duration=3' "
            "-c:v libx264 -preset fast -pix_fmt yuv420p "
            f"{busy_clip_abs}",
            file=sys.stderr,
        )
        return 1

    # --- Render (a): with busy clip ---
    print("[gate] rendering with-clip spec …")
    stage_spec(base_spec(with_clip=True))
    render_still("with-clip", RENDER_FRAME, png_clip)

    # --- Render (b): gradient-only baseline ---
    print("[gate] rendering baseline (no clip) spec …")
    stage_spec(base_spec(with_clip=False))
    render_still("baseline", RENDER_FRAME, png_base)

    # --- Compute min-tile contrast ---
    print("[gate] computing per-tile contrast …")
    c_clip, n_clip = tile_min_contrast(png_clip)
    c_base, n_base = tile_min_contrast(png_base)

    threshold = c_base * TOLERANCE

    print(f"\n[gate] text-bearing tiles evaluated — with-clip: {n_clip}, baseline: {n_base}")
    print(f"[gate] min-tile contrast — with-clip : {c_clip:.4f}")
    print(f"[gate] min-tile contrast — baseline  : {c_base:.4f}")
    print(f"[gate] required threshold (×{TOLERANCE})   : {threshold:.4f}")

    if c_clip >= threshold:
        print(
            f"\n[gate] PASS — with-clip ({c_clip:.4f}) ≥ baseline × {TOLERANCE} ({threshold:.4f}). "
            "Scrim keeps worst-case local legibility within striking distance of the opaque card."
        )
        return 0
    else:
        print(
            f"\n[gate] FAIL — with-clip ({c_clip:.4f}) < baseline × {TOLERANCE} ({threshold:.4f}). "
            "Increase SCRIM_ALPHA or reduce GRADIENT_OPACITY_WITH_CLIP in heroBackdropUtils.ts.",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    sys.exit(main())
